version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: meubanco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senhauser
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rede-local

volumes:
  mysql_data:

networks:
  rede-local:
    driver: bridge
